### ISSUE TITLE
OAuth Rabbit Hole

### ISSUE THREAD

**Issue by SiouxsieAsylum** [SiouxsieAsylum/Invoicer#2]
Realized I absolutely need Oauth to get this to work, but I feel like the documentation really isn't all that clear (probably why you guys didn't touch it, which is fair) but I could use someone to help me dissect it. There are a lot of options and I have no idea which ones I should be taking.

**Comment by jsm13** [comment]
What service are you trying to auth with? You'll pick your oauth strategy based on the oauth provider you're using.

**Comment by SiouxsieAsylum** [comment]
I'm using passport oauth2 for both google and yahoo. I'm not sure they're too different configuration wise, and I yarn added the `passport-google-oauth2` and `passport-yahoo-oauth2` modules. Both look fine, but I don't really know enough about the code and process itself to connect it to the front end or even really test it in postman. Are you free just to help me dissect it sometime soon or are you out of commission for the day

**Comment by jsm13** [comment]
Have you set up tokens in the developer portals at google and yahoo?

**Comment by SiouxsieAsylum** [comment]
Yep for both, and they're in my .env file

**Comment by jsm13** [comment]
I'd actually do just google the rest of the way and then come back and do yahoo once google is working. Next you'll want to configure the google strategy in another file in the `auth/` directory next to the local strategy. Checkout configuration under the oauth2 strategy here (http://www.passportjs.org/docs/google/)

**Comment by SiouxsieAsylum** [comment]
I mean I have the code from the strategy creation and routes in my app (in "google.js" and "yahoo.js" respectively) but I just am not sure what the code actually does so I don't know how to configure it to what my app needs to do

**Comment by SiouxsieAsylum** [comment]
Like I'm not sure whats vital and what isn't so I don't know how to modify it

**Comment by jsm13** [comment]
Could you make a work in progress commit and push that up. In the configuration section there pretty much all of it is important. The thing that it glosses over is that find or create method which you'll want to define in more detail. If you just set up the bit around that though you can see what the  `accessToken`, `refreshToken`, and `profile` look like and decide what you want to persist

**Comment by jsm13** [comment]
This looks good so far. And when you go to `/auth/google` do you get redirected properly?
